spring:
  data:
    rest:
      base-path: /api
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
mock-user:
#  as: "prescriber@meraklis.io"
  as: "test@meraklis.io"
